configMap:
  enabled: true
container:
  port: 80
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi
containerPort: 80
deployment:
  replicaCount: 1
image:
  pullPolicy: IfNotPresent
  repository: nginx
  tag: latest
ingress:
  enabled: false
replicaCount: 1
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi
service:
  enabled: true
  port: 80
  type: ClusterIP
